# Site settings
title: Sydney

clients:
  - name: Qantas
    logo: qantas.svg
    link: "https://ad.doubleclick.net/ddm/clk/457573948;261709344;x"

  - name: Destination New South Wales
    logo: dnsw.svg
    link: "https://www.visitnsw.com/"

core-se-link: https://www.secretescapes.com/current-sales
description: >
  From wanderlust-inspiring beaches to the bustling sprawl of Australia’s favourite urban escape, New South Wales harbours adventures for all tastes.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site

# REMEMBER LIVE URL EXCEPTION: mp.se.com/qantas-new-south-wales/
baseurl: "/uk/2019/qantas-new-south-wales" # the subpath of your site, e.g. /blog/
img:     "/uk/2019/qantas-new-south-wales/_assets/img"
css:     "/uk/2019/qantas-new-south-wales/_assets/css"
js:      "/uk/2019/qantas-new-south-wales/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed